from utils.aws import getting_data_from_AWS_RDS, update_data_to_AWS_S3, upload_class_data_AWS_S3
from utils.stats import statistical_summary, correlation_matrix, plot_categorical_features
from utils.stats import plot_categorical_heatmap, plot_clustered_bars, plot_categorical_numerical_interactions
from utils.stats import scatterplot_matrix_numeric
from utils.ML import model_figures, model_assessment
from utils.various import load_credentials